CREATE OR REPLACE PROCEDURE Process_TopUp (
    p_player_id IN NUMBER,
    p_item_id IN NUMBER
) AS
    v_wallet_balance NUMBER;
    v_item_price NUMBER;
BEGIN
    SELECT wallet_balance
    INTO v_wallet_balance
    FROM Players
    WHERE player_id = p_player_id;

    SELECT price
    INTO v_item_price
    FROM TopUp_Items
    WHERE item_id = p_item_id;

    IF v_wallet_balance >= v_item_price THEN
        UPDATE Players
        SET wallet_balance = wallet_balance - v_item_price
        WHERE player_id = p_player_id;

        INSERT INTO Orders (player_id, item_id, status)
        VALUES (p_player_id, p_item_id, 'Completed');

        DBMS_OUTPUT.PUT_LINE('Top-up successful! Wallet updated.');
        COMMIT;
    ELSE
        INSERT INTO Orders (player_id, item_id, status)
        VALUES (p_player_id, p_item_id, 'Failed');

        DBMS_OUTPUT.PUT_LINE('Top-up failed: Insufficient balance.');
        COMMIT;
    END IF;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Error: Player ID or Item ID does not exist.');
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('An unexpected error occurred.');
END;
/
SQL> CREATE OR REPLACE FUNCTION Get_Total_Revenue
  2  RETURN NUMBER AS
  3      v_total NUMBER := 0;
  4  BEGIN
  5      SELECT NVL(SUM(i.price), 0) INTO v_total
  6      FROM Orders o
  7      JOIN TopUp_Items i ON o.item_id = i.item_id
  8      WHERE o.status = 'Completed';
  9
 10      RETURN v_total;
 11  EXCEPTION
 12      WHEN OTHERS THEN
 13          RETURN 0;
 14  END;
 15  /

Function created.
SQL> CREATE TABLE Audit_Log (
  2      log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  3      username VARCHAR2(100),
  4      action_type VARCHAR2(50),
  5      action_date DATE DEFAULT SYSDATE
  6  );

Table created.
CREATE OR REPLACE TRIGGER Secure_Players_Trigger
BEFORE INSERT OR UPDATE OR DELETE ON Players
FOR EACH ROW
DECLARE
    v_holiday_count NUMBER;
    v_day_name VARCHAR2(20);
BEGIN
    v_day_name := TO_CHAR(SYSDATE, 'DAY');

    SELECT COUNT(*)
    INTO v_holiday_count
    FROM Public_Holidays
    WHERE TRUNC(holiday_date) = TRUNC(SYSDATE);

    IF TRIM(v_day_name) IN ('SATURDAY', 'SUNDAY') OR v_holiday_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'DML operations are restricted during weekends and public holidays for security.');
    END IF;

    IF INSERTING THEN
        INSERT INTO Audit_Log (username, action_type)
        VALUES (USER, 'INSERT');
    ELSIF UPDATING THEN
        INSERT INTO Audit_Log (username, action_type)
        VALUES (USER, 'UPDATE');
    ELSIF DELETING THEN
        INSERT INTO Audit_Log (username, action_type)
        VALUES (USER, 'DELETE');
    END IF;
END;
/
CREATE OR REPLACE PACKAGE Gaming_TopUp_Pkg AS

    FUNCTION Is_System_Blocked RETURN BOOLEAN;

    PROCEDURE Process_Player_TopUp (
        p_tx_id IN INT,
        p_player_id IN INT,
        p_game_id IN INT,
        p_amount IN NUMBER
    );

END Gaming_TopUp_Pkg;
/
CREATE OR REPLACE PACKAGE BODY Gaming_TopUp_Pkg AS

    FUNCTION Is_System_Blocked RETURN BOOLEAN IS
        v_holiday_count INT;
        v_day_name VARCHAR2(20);
    BEGIN
        v_day_name := TO_CHAR(SYSDATE, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH');

        IF v_day_name IN ('SAT', 'SUN') THEN
            RETURN TRUE;
        END IF;

        SELECT COUNT(*)
        INTO v_holiday_count
        FROM Public_Holidays
        WHERE TRUNC(holiday_date) = TRUNC(SYSDATE);

        IF v_holiday_count > 0 THEN
            RETURN TRUE;
        END IF;

        RETURN FALSE;
    END Is_System_Blocked;

    PROCEDURE Process_Player_TopUp (
        p_tx_id IN INT,
        p_player_id IN INT,
        p_game_id IN INT,
        p_amount IN NUMBER
    ) IS
    BEGIN
        IF Is_System_Blocked() THEN
            RAISE_APPLICATION_ERROR(-20003, 'System Lock: Cannot process transactions during weekends or holidays.');
        ELSE
            INSERT INTO Transactions (tx_id, player_id, game_id, amount, status)
            VALUES (p_tx_id, p_player_id, p_game_id, p_amount, 'Completed');

            COMMIT;

            DBMS_OUTPUT.PUT_LINE('Transaction ' || p_tx_id || ' processed successfully via Package.');
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            DBMS_OUTPUT.PUT_LINE('Transaction Failed in Package: ' || SQLERRM);
    END Process_Player_TopUp;

END Gaming_TopUp_Pkg;
/


