SQL> CONNECT "31314_Hassan_GamingTopUp_DB"/2006;
Connected.
SQL> CREATE TABLE Players (
  2      player_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  3      username VARCHAR2(50) NOT NULL UNIQUE,
  4      email VARCHAR2(100) NOT NULL UNIQUE,
  5      wallet_balance NUMBER(10,2) DEFAULT 0.00 CHECK (wallet_balance >= 0),
  6      registration_date DATE DEFAULT SYSDATE
  7  );

Table created.

SQL> CREATE TABLE Games (
  2      game_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  3      game_name VARCHAR2(100) NOT NULL UNIQUE,
  4      developer VARCHAR2(100),
  5      status VARCHAR2(20) DEFAULT 'Active' CHECK (status IN ('Active', 'Maintenance'))
  6  );

Table created.

SQL> CREATE TABLE TopUp_Items (
  2      item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  3      game_id NUMBER NOT NULL,
  4      item_name VARCHAR2(100) NOT NULL,
  5      price NUMBER(10,2) NOT NULL CHECK (price > 0),
  6      diamonds_or_uc NUMBER NOT NULL CHECK (diamonds_or_uc > 0),
  7      CONSTRAINT fk_items_game FOREIGN KEY (game_id) REFERENCES Games(game_id) ON DELETE CASCADE
  8  );

Table created.

SQL> CREATE TABLE Orders (
  2      order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  3      player_id NUMBER NOT NULL,
  4      item_id NUMBER NOT NULL,
  5      order_date DATE DEFAULT SYSDATE,
  6      status VARCHAR2(20) DEFAULT 'Pending' CHECK (status IN ('Pending', 'Completed', 'Failed')),
  7      CONSTRAINT fk_orders_player FOREIGN KEY (player_id) REFERENCES Players(player_id) ON DELETE CASCADE,
  8      CONSTRAINT fk_orders_item FOREIGN KEY (item_id) REFERENCES TopUp_Items(item_id) ON DELETE CASCADE
  9  );

Table created.

SQL> CREATE TABLE Public_Holidays (
  2      holiday_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  3      holiday_name VARCHAR2(100) NOT NULL,
  4      holiday_date DATE NOT NULL UNIQUE
  5  );

Table created.

SQL> INSERT INTO Players (username, email, wallet_balance) VALUES ('hassan_pro', 'hassan@email.com', 150.00);

1 row created.

SQL> INSERT INTO Players (username, email, wallet_balance) VALUES ('gamer_rw', 'gamer@email.com', 10.00);

1 row created.

SQL> INSERT INTO Players (username, email, wallet_balance) VALUES ('alpha_one', 'alpha@email.com', 75.50);

1 row created.

SQL> INSERT INTO Games (game_name, developer) VALUES ('Free Fire', 'Garena');

1 row created.

SQL> INSERT INTO Games (game_name, developer) VALUES ('PUBG Mobile', 'Tencent');

1 row created.

SQL> INSERT INTO Games (game_name, developer) VALUES ('Valorant', 'Riot Games');

1 row created.

SQL> INSERT INTO TopUp_Items (game_id, item_name, price, diamonds_or_uc) VALUES (1, '100 Diamonds', 1.99, 100);

1 row created.

SQL> INSERT INTO TopUp_Items (game_id, item_name, price, diamonds_or_uc) VALUES (1, '500 Diamonds', 4.99, 500);

1 row created.

SQL> INSERT INTO TopUp_Items (game_id, item_name, price, diamonds_or_uc) VALUES (2, '60 UC', 0.99, 60);

1 row created.

SQL> INSERT INTO TopUp_Items (game_id, item_name, price, diamonds_or_uc) VALUES (2, '660 UC', 9.99, 660);

1 row created.

SQL> INSERT INTO Orders (player_id, item_id, status) VALUES (1, 2, 'Completed');

1 row created.

SQL> INSERT INTO Orders (player_id, item_id, status) VALUES (2, 3, 'Pending');

1 row created.

SQL> INSERT INTO Public_Holidays (holiday_name, holiday_date) VALUES ('New Year', TO_DATE('2026-01-01', 'YYYY-MM-DD'));

1 row created.

SQL> COMMIT;

Commit complete